services:
  app:
    build:
      context: .
      dockerfile: DockerFile
      args:
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
        SANITY_API_READ_TOKEN: ${SANITY_API_READ_TOKEN}
        RESEND_API_KEY: ${RESEND_API_KEY}
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
