import type { Metadata } from "next";

import { Saira } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import Header from "@/components/header";

const saira = Saira({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Jhony Monteiro | Software engineer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true} className="scroll-smooth">
      <body className={`${saira.className} antialiased`}>
        <Header />
        <main>{children}</main>
        <footer className="mb-12 mt-32 text-center text-gray">
          <p>© 2024 - All rights reserved</p>
        </footer>
      </body>
    </html>
  );
}
