// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  services: dynamic(() => import("./Services")),
  projects: dynamic(() => import("./Projects")),
  journey: dynamic(() => import("./Journey")),
  recommendations: dynamic(() => import("./Recommendations")),
};
